# Generated by Django 5.0.1 on 2024-01-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='flag_icon',
            new_name='unicodeFlag',
        ),
    ]
